name: Publish Native Windows

on:
  workflow_call:

jobs:
  build-windows-native:
    uses: ./.github/workflows/publish-native-platform.yml
    with:
      platform_name: Windows
      runs_on: windows-latest
      artifact_name: kustomtrace-cli-windows-x64
      archive_name: kustomtrace-windows-x64.zip
      archive_format: zip
      release_binary_name: kustomtrace-windows-x64.exe
      binary_name: kustomtrace.exe
      gradle_command: .\gradlew.bat
    secrets: inherit
