name: Publish Native Linux

on:
  workflow_call:

jobs:
  build-linux-native:
    uses: ./.github/workflows/publish-native-platform.yml
    with:
      platform_name: Linux
      runs_on: ubuntu-latest
      artifact_name: kustomtrace-cli-linux-x64
      archive_name: kustomtrace-linux-x64.tar.gz
      archive_format: tar.gz
      release_binary_name: kustomtrace-linux-x64
      binary_name: kustomtrace
      gradle_command: ./gradlew
    secrets: inherit
